<?php
$record = $block->getEditRecord();
?>
<form action="<?= $block->getUrl('crud/index/save'); ?>" method = "post">
  <label for="name">Name:</label><br>
  <input type="text" id="name" name="name"><br><br>
  
  <label for="post_content">Post content:</label><br>
  <input type="text" id="post_content" name="post_content"><br><br>
  
  <label for="text">url_key:</label><br>
  <input type="text" id="url_key" name="url_key"><br><br>
  
  <label for="text">tags:</label><br>
  <input type="text" id="tags" name="tags"><br><br>

  <label for="text">Post_content:</label><br>
  <input type="text" id="post_content" name="post_content"><br><br>
  
  <input type="hidden" name="editRecordId" value=""><br><br>
  <input type="submit" name="add record">
</form>